homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.0.0/24
 # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 63
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include_dir_merge_named customizations


config:
default_config:


#Config Split
alert: !include_dir_merge_named alerts
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include cameras.yaml
cover: !include_dir_merge_list covers
device_tracker: !include device_tracker.yaml
google_assistant: !include Google_Assistant.yaml
group: !include_dir_merge_named groups
influxdb: !include influxdb.yaml
input_datetime: !include_dir_merge_named input_datetime
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
input_text: !include_dir_merge_named input_text
input_boolean: !include_dir_merge_named input_boolean
ios: !include iOS.yaml
light: !include_dir_merge_list lights
media_player: !include media_player/media_player.yaml
mobile_app: !include iOS.yaml
notify: !include notify.yaml
scene: !include_dir_merge_named scenes
script: !include_dir_merge_named scripts
shell_command: !include_dir_merge_named shell_commands
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include zones.yaml


alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code
    pending_time: 30

bmw_connected_drive:
  220d:
    username: !secret bmw_connected_drive_username
    password: !secret bmw_connected_drive_password
    region: "rest_of_world"


climate:
  - platform: mqtt
    name: Anova
    modes:
      - disconnected
      - stopped
      - running
    qos: 1
    initial: 19
    current_temperature_topic: anova/status
    current_temperature_template: "{{ value_json.current_temp }}"
    temperature_state_topic: anova/status
    temperature_state_template: "{{ value_json.target_temp }}"
    mode_state_topic: anova/status
    mode_state_template: "{{ value_json.state }}"
    mode_command_topic: anova/command/run
    temperature_command_topic: anova/command/temp

counter:
  iosbadgecount:
    initial: 0
    step: 1
    name: iOS Badge Count
    icon: mdi:numeric-1-box


discovery:

ffmpeg:

frontend: 

google:
  client_id: !secret GCal_ID
  client_secret: !secret GCal_Secret

hacs:
  token: !secret hacs_token

history:
  # exclude:
    # domains:
      # - automation

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: false
  login_attempts_threshold: 3

ifttt:
  key: !secret ifttt_key


life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  driving_speed: 18
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3
  prefix: ''


logbook:

# Logging level
# enable_debug:
logger:
  default: error
  logs:
    miio.device: critical
    # homeassistant.components.rfxtrx: debug
    # homeassistant.helpers.entity: critical
    # custom_components.currentcost: debug
    homeassistant.components.xiaomi_miio.light: critical
    homeassistant.components.xiaomi_miio.switch: critical
    homeassistant.components.bmw_connected_drive: critical
    homeassistant.components.shell_command: critical
    homeassistant.components.scrape: critical
    homeassistant.components.rest: critical
    homeassistant.components.waze_travel_time: critical


lovelace:
  mode: yaml
  resources:
      #Kiosk mode for Alarm panel https://gist.github.com/ciotlosm/1f09b330aa5bd5ea87b59f33609cc931
    - url: /local/kiosk.js?v=1.1
      type: js
      # https://github.com/thomasloven/lovelace-card-tools
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
      # fold-entity https://github.com/thomasloven/lovelace-fold-entity-row
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: js
      #auto-entities  https://github.com/thomasloven/lovelace-auto-entities
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
      #Mini media player https://github.com/kalkih/mini-media-player
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
      #Vertical Stack https://github.com/custom-cards/vertical-stack-in-card
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
      # Fully Kiosk https://github.com/thomasloven/lovelace-fullykiosk
    # - url: /local/lovelace-fullykiosk.js
      # type: js
    # - url: /local/kiosk-config.js
      # type: js
      # Animated Weather Card https://github.com/bramkragten/weather-card
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
      # Home Feed Card Card https://github.com/gadgetchnnel/lovelace-home-feed-card
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: js

      # Compact Custom Header https://github.com/maykar/custom-header
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    # - url: /local/compact-custom-header.js?v=0.0.1
      # type: js

    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: js
      
    # Lovelace Card Preloader
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module
  # dashboards:
    # lovelace-alarm-panel: # Needs to contain a hyphen (-)
      # mode: yaml
      # filename: lovelace-alarm.yaml
      # title: Alarm Panel
      # icon: mdi:shield-check
      # show_in_sidebar: true
      # require_admin: false
    # lovelace-home: # Needs to contain a hyphen (-)
      # mode: yaml
      # filename: lovelace-home.yaml
      # title: Home
      # icon: mdi:home
      # show_in_sidebar: true
      # require_admin: true


map:

mqtt:
  client_id: home-assistant-1
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

person:
  - name: Laurent
    id: laurent
    user_id: !secret ha_lolo_user_id
    device_trackers:
      - device_tracker.laurent
      # - device_tracker.lolos_iphone
      # - device_tracker.laurent_mah_iphone_5s
      # - device_tracker.lolosiphone
  - name: Div
    id: divashni
    user_id: !secret ha_div_user_id
    device_trackers:
      - device_tracker.divashni
      # - device_tracker.div_iphone
      # - device_tracker.diviphone

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETWB5-if00-port0

recorder:
  db_url: !secret db_url

shopping_list:

ssdp:

# stream:

sun:

system_health:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-uk'

updater:
  include_used_components: True

vacuum:
- platform: xiaomi_miio
  name: 'Mi Robot Vacuum'
  host: 192.168.0.18
  token: !secret xiaomi_token_vacuum

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
 
webhook:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_mac
      key: !secret xiaomi_aqara_password
      host: 192.168.0.5

zeroconf:

zigbee2mqtt_networkmap:
  #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key