- alias: Blinds - Open When Not Dark
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.dark
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds

- alias: Blinds - Close When Dark
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.dark
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds
