- alias: Turn Onkyo Off When Stop Playing On ChromeCast
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.house
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.conservatory
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.kitchen
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.onkyo
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.onkyo_tx_nr656
    to: 'off'
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: media_player.house
      state: 'off'
    - condition: state
      entity_id: media_player.conservatory
      state: 'off'
    - condition: state
      entity_id: media_player.kitchen
      state: 'off'
  action:
  - service: media_player.turn_off
    entity_id: media_player.onkyo_tx_nr656

- alias: Turn Onkyo On When TV Goes On
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.panasonic_viera_tv
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.panasonic_viera_tv
      volume_level: '0' 
  - service: media_player.turn_on
    entity_id: media_player.onkyo_tx_nr656