
- platform: kodi
  host: 192.168.0.28
- platform: onkyo
  host: 192.168.0.26
  name: Onkyo TX-NR656
  sources:
    video6: 'Main PC'
    bluray: 'Blu-Ray'
    video2: 'Sky'
    network: 'ChromeCast'
    tv: 'TV'
    strm-box: 'Stream-Box/CC'
- platform: panasonic_viera
  host: 192.168.0.27
  mac: D8:AF:F1:47:7A:16
- platform: mpd
  host: 192.168.0.21
  port: 6600
  name: MPD RPi Kitchen
- platform: androidtv
  host: 192.168.0.28
  name: Mi Box3 ADTV
- platform: androidtv
  host: 192.168.0.29
  name: Fire Stick 4K